//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------




[System.ServiceModel.MessageContractAttribute()]
public class ftomRequest
{
    
    [System.ServiceModel.MessageBodyAttribute(Name="ftom", Namespace="http://tempuri.org/", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Order=0)]
    public ftomRequestBody Body;
    
    public ftomRequest()
    {
    }
    
    public ftomRequest(ftomRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public class ftomRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public double f;
    
    public ftomRequestBody()
    {
    }
    
    public ftomRequestBody(double f)
    {
        this.f = f;
    }
}

[System.ServiceModel.MessageContractAttribute()]
public class ftomResponse
{
    
    [System.ServiceModel.MessageBodyAttribute(Name="ftomResponse", Namespace="http://tempuri.org/", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Order=0)]
    public ftomResponseBody Body;
    
    public ftomResponse()
    {
    }
    
    public ftomResponse(ftomResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public class ftomResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public double ftomResult;
    
    public ftomResponseBody()
    {
    }
    
    public ftomResponseBody(double ftomResult)
    {
        this.ftomResult = ftomResult;
    }
}

[System.ServiceModel.MessageContractAttribute()]
public class mtofRequest
{
    
    [System.ServiceModel.MessageBodyAttribute(Name="mtof", Namespace="http://tempuri.org/", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Order=0)]
    public mtofRequestBody Body;
    
    public mtofRequest()
    {
    }
    
    public mtofRequest(mtofRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public class mtofRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public double m;
    
    public mtofRequestBody()
    {
    }
    
    public mtofRequestBody(double m)
    {
        this.m = m;
    }
}

[System.ServiceModel.MessageContractAttribute()]
public class mtofResponse
{
    
    [System.ServiceModel.MessageBodyAttribute(Name="mtofResponse", Namespace="http://tempuri.org/", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Order=0)]
    public mtofResponseBody Body;
    
    public mtofResponse()
    {
    }
    
    public mtofResponse(mtofResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
public class mtofResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public double mtofResult;
    
    public mtofResponseBody()
    {
    }
    
    public mtofResponseBody(double mtofResult)
    {
        this.mtofResult = mtofResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute()]
public interface IMetricImperial
{
    
    // CODEGEN: Generating message contract since message part ftomResult requires protection.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetricImperial/ftom", ReplyAction="http://tempuri.org/IMetricImperial/ftomResponse")]
    ftomResponse ftom(ftomRequest request);
    
    // CODEGEN: Generating message contract since message part mtofResult requires protection.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetricImperial/mtof", ReplyAction="http://tempuri.org/IMetricImperial/mtofResponse")]
    mtofResponse mtof(mtofRequest request);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IMetricImperialChannel : IMetricImperial, System.ServiceModel.IClientChannel
{
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class MetricImperialProxy : System.ServiceModel.ClientBase<IMetricImperial>, IMetricImperial
{
    
    public MetricImperialProxy()
    {
    }
    
    public MetricImperialProxy(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MetricImperialProxy(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MetricImperialProxy(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MetricImperialProxy(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    ftomResponse IMetricImperial.ftom(ftomRequest request)
    {
        return base.InnerProxy.ftom(request);
    }
    
    public double ftom(double f)
    {
        ftomRequest inValue = new ftomRequest();
        inValue.Body = new ftomRequestBody();
        inValue.Body.f = f;
        ftomResponse retVal = ((IMetricImperial)(this)).ftom(inValue);
        return retVal.Body.ftomResult;
    }
    
    mtofResponse IMetricImperial.mtof(mtofRequest request)
    {
        return base.InnerProxy.mtof(request);
    }
    
    public double mtof(double m)
    {
        mtofRequest inValue = new mtofRequest();
        inValue.Body = new mtofRequestBody();
        inValue.Body.m = m;
        mtofResponse retVal = ((IMetricImperial)(this)).mtof(inValue);
        return retVal.Body.mtofResult;
    }
}
